/* Regenerate deterministic standalone SVG fallbacks: node build_static.js */
const fs=require('fs'),path=require('path'),vm=require('vm');
const win={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'common.js'),'utf8'),{window:win});const M=win.Lecture3D;
const seed=20260928,Q=M.cloud(seed),randK=M.rng(seed+1),K=Q.map(p=>({xyz:p.xyz.map(v=>v+.23*M.gaussian(randK))}));
const randB=M.rng(seed+2),trueR=M.rotation(68,-22,13),shift=[.42,-.36,.25],B=Q.map(p=>({xyz:M.add(M.vec(p.xyz,trueR),shift).map(v=>v+.075*M.gaussian(randB))}));
const anchors=[8,24,40],fit=M.procrustes(anchors.map(i=>Q[i].xyz),anchors.map(i=>B[i].xyz));
const hidden=Q.map((_,i)=>i).filter(i=>!anchors.includes(i)),targets=hidden.map(i=>B[i].xyz);
const hits=(f)=>hidden.reduce((n,i)=>n+(hidden[M.nearest(f?fit.transform(Q[i].xyz):Q[i].xyz,targets)]===i),0);
const fmt=x=>x.toFixed(3),xyz=p=>'('+p.map(fmt).join(', ')+')';
function chart(sets){const target={innerHTML:''};M.render(target,sets);return target.innerHTML;}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function mathLabels(s){return esc(s).replace(/\b(E|e)_(in|out)\b/g,(_,letter,role)=>`<tspan font-weight="700">${letter}</tspan><tspan baseline-shift="sub" font-size="75%">${role}</tspan>`).replace(/\b(R|I|e)\b/g,'<tspan font-weight="700">$1</tspan>');}
function write(name,title,subtitle,chartHtml,lines,foot){const tx=(x,y,s,cls='body')=>{const sizes={title:38,sub:21,body:23,small:19,value:26};const colors={title:'#f2f6ff',sub:'#b4c4d9',body:'#f2f6ff',small:'#b4c4d9',value:'#a9e879'};return `<text x="${x}" y="${y}" class="${cls}" fill="${colors[cls]}" font-size="${sizes[cls]}" font-family="Arial" font-weight="${cls==='title'||cls==='value'?700:400}">${mathLabels(s)}</text>`;};let out=`<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720"><style><![CDATA[.title{font:700 38px Arial;fill:#f2f6ff}.sub{font:21px Arial;fill:#b4c4d9}.body{font:23px Arial;fill:#f2f6ff}.small{font:19px Arial;fill:#b4c4d9}.value{font:700 26px Arial;fill:#a9e879}.axes line{stroke:#7790a8;stroke-width:2}.axes text{fill:#b4c4d9;font:700 20px Arial}.mark{fill:#59d6e6;opacity:.8;stroke:#122332;stroke-width:1.2}.mark.set1{fill:#ffad64}.mark.selected{fill:#a9e879;stroke:#fff;stroke-width:2.5;opacity:1}.point-label{fill:#fff;font:700 17px Arial;paint-order:stroke;stroke:#172238;stroke-width:4px}]]></style><rect width="1280" height="720" fill="#111724"/>${tx(32,55,title,'title')}${tx(32,86,subtitle,'sub')}<rect x="24" y="112" width="820" height="520" rx="14" fill="#1c2636" stroke="#40516a"/><g transform="translate(32 120)">${chartHtml}</g><rect x="856" y="112" width="400" height="520" rx="14" fill="#1c2636" stroke="#40516a"/>`;lines.forEach((l,i)=>{out+=tx(878,159+i*58,l,i%2?'value':'small');});out+=tx(32,671,foot,'small')+'</svg>';fs.writeFileSync(path.join(__dirname,name),out);}
for(const [label,R] of [['before',M.rotation(0,0,0)],['after',M.rotation(40,20,-15)]]){const q=Q.map(p=>({xyz:M.vec(p.xyz,R)})),k=K.map(p=>({xyz:M.vec(p.xyz,R)})),i=0,j=1,h=0;const d0=M.norm(M.sub(Q[i].xyz,Q[j].xyz)),d1=M.norm(M.sub(q[i].xyz,q[j].xyz));const c=(a,b)=>M.dot(a,b)/(M.norm(a)*M.norm(b));const score0=M.dot(Q[i].xyz,K[h].xyz),score1=M.dot(q[i].xyz,k[h].xyz);write(`rotation_${label}.svg`,`Совместный поворот таблиц · ${label==='before'?'до':'после'}`,'Синтетические данные: 48 входных и 48 контекстных векторов',chart([{points:q,selected:[i,j],labels:{[i]:'вход w01',[j]:'вход w02'}},{points:k,selected:[h],labels:{[h]:'контекст w01'}}]),['e_in(w01): '+xyz(q[i].xyz),'Расст.: '+fmt(d0)+' → '+fmt(d1),'Косинус: '+fmt(c(Q[i].xyz,Q[j].xyz))+' → '+fmt(c(q[i].xyz,q[j].xyz)),'Score: '+fmt(score0)+' → '+fmt(score1),'Углы: 40°, 20°, −15°','det R = +1; RᵀR = I'],'Векторы – столбцы: e′ = R e. Камера неподвижна.');}
const rms0=Math.sqrt(anchors.reduce((s,i)=>s+M.norm(M.sub(Q[i].xyz,B[i].xyz))**2,0)/anchors.length);for(const label of ['before','after']){const aligned=label==='after',points=Q.map(p=>({xyz:aligned?fit.transform(p.xyz):p.xyz}));write(`procrustes_${label}.svg`,`Выравнивание по трём парам · ${aligned?'после':'до'}`,'Синтетические данные: 48 пар, фиксированные поворот, сдвиг и шум',chart([{points,selected:anchors,labels:Object.fromEntries(anchors.map(i=>[i,Q[i].id]))},{points:B,selected:[],labels:{}}]),['Якоря: w09, w25, w41','RMS: '+fmt(rms0)+' → '+fmt(fit.residual),'Скрыто: '+hidden.length+' пар','Верных: '+hits(false)+' → '+hits(true),'Метрика: Euclidean','Кандидаты: скрытые B'],'Поворот действует на столбцы. Центры считаем по якорям. Шум оставляет ошибку.');}
console.log('Wrote four SVG fallbacks.');
