/* Run with node test_math.js. No browser or network required. */
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const win={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'common.js'),'utf8'),{window:win});const M=win.Lecture3D;
const close=(a,b,tol=1e-9)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
const seed=20260928,Q=M.cloud(seed),randK=M.rng(seed+1),K=Q.map(p=>p.xyz.map(v=>v+.23*M.gaussian(randK))),R=M.rotation(40,20,-15),q=Q.map(p=>M.vec(p.xyz,R)),k=K.map(p=>M.vec(p,R));
close(M.det(R),1);for(let i=0;i<Q.length;i++){for(let j=0;j<Q.length;j++){close(M.norm(M.sub(Q[i].xyz,Q[j].xyz)),M.norm(M.sub(q[i],q[j])));close(M.dot(Q[i].xyz,Q[j].xyz),M.dot(q[i],q[j]));close(M.dot(Q[i].xyz,K[j]),M.dot(q[i],k[j]));}}
const trueR=M.rotation(68,-22,13),shift=[.42,-.36,.25],randB=M.rng(seed+2),noise=.075,B=Q.map(p=>M.add(M.vec(p.xyz,trueR),shift).map(v=>v+noise*M.gaussian(randB))),anchors=[8,24,40],fit=M.procrustes(anchors.map(i=>Q[i].xyz),anchors.map(i=>B[i]));assert.ok(fit.ok);close(fit.detR,1,1e-8);close(fit.residual,.07636798056471306,1e-9);
const noiseless=Q.map(p=>M.add(M.vec(p.xyz,trueR),shift)),exact=M.procrustes(anchors.map(i=>Q[i].xyz),anchors.map(i=>noiseless[i]));assert.ok(exact.ok);close(exact.residual,0);for(let i=0;i<3;i++)for(let j=0;j<3;j++)close(exact.R[i][j],trueR[i][j]);
const line=[[0,0,0],[1,0,0],[2,0,0]];assert.equal(M.procrustes(line,line).ok,false);
const reflected=Q.slice(0,8).map(p=>[-p.xyz[0],p.xyz[1],p.xyz[2]]),proper=M.procrustes(Q.slice(0,8).map(p=>p.xyz),reflected);assert.ok(proper.ok);close(proper.detR,1,1e-8);assert.ok(proper.residual>.1);
const hidden=Q.map((_,i)=>i).filter(i=>!anchors.includes(i)),pool=hidden.map(i=>B[i]);const hits=aligned=>hidden.reduce((n,i)=>n+(hidden[M.nearest(aligned?fit.transform(Q[i].xyz):Q[i].xyz,pool)]===i),0);assert.equal(hits(false),3);assert.equal(hits(true),43);
const cos=(a,b)=>M.dot(a,b)/(M.norm(a)*M.norm(b));close(cos(Q[0].xyz,B[0]),.17631035854020158,1e-10);close(cos(fit.transform(Q[0].xyz),B[0]),.999871508310423,1e-10);
for(const page of ['rotation','procrustes']){const html=fs.readFileSync(path.join(__dirname,page+'.html'),'utf8'),script=html.match(/<script>\s*([\s\S]*?)<\/script><\/body>/)[1],elements=new Map();function el(id){if(!elements.has(id))elements.set(id,{value:'0',innerHTML:'',textContent:'',dataset:{},classList:{toggle(){}},addEventListener(){},querySelectorAll(){return[]}});return elements.get(id)}const window={Lecture3D:M,print(){}};const document={getElementById:el};vm.runInNewContext(script,{window,document,console});assert.ok(page==='rotation'?window.LectureRotation.getState().rotatedQ.length===48:window.LectureProcrustes.getState().source.length===48);if(page==='procrustes'){const chooser=elements.get('pairs').innerHTML;for(const id of ['b09','b25','b41'])assert.ok(chooser.includes(id));for(const id of ['b01','b03','b06','b17','b33'])assert.ok(!chooser.includes(id));assert.equal((chooser.match(/пара скрыта/g)||[]).length,5);assert.ok(!elements.get('examples').textContent.includes('b01'));window.LectureProcrustes.selectAnchors([0,2,5]);const updated=elements.get('pairs').innerHTML;for(const id of ['b01','b03','b06'])assert.ok(updated.includes(id));for(const id of ['b09','b25','b41'])assert.ok(!updated.includes(id));assert.equal(window.LectureProcrustes.getState().selected.length,3);}}
console.log('OK: rotation invariants; SO(3) fit and degeneracy; fixed hidden retrieval; page initialization.');
